@startuml
entity Project {
  * projectId: String (Hash)
  --
  name: String
  description: String
  status: String
}

entity Tickets {
  * projectId: String (Hash)
  ..
  * followedUser: String (Range)
  ..
  name: String
  description: String
  status: String
}

Project "1" --{ "0..*  " Tickets
@enduml