@startuml

entity User as "User" {
  *userId
  ---
  +firstName
  +lastName
  +company
  +email

}

entity Project as "Project" {
  *projectId
  ---
  *owner: String (userId)
  *dateCreated: Date
  *title: String
  description: String
  dueDate: Date
  tasksCompleted: Integer
  totalTask: Integer
  topContributor: String (userId)
}

entity Member as "Member" {
  *projectId
  *userId
  ---
  +firstName
  +lastName
  +role
  +company
  +email
}

entity Task as "Task" {
  +TaskID
  +TaskName
  +Description
  +Status
  +DueDate
  +AssignedTo (UserID)
  +CreatedBy (UserID)
}

entity Role as "Role" {
  +RoleID
  +RoleName
  +Description
  +Permissions
}

Member --o{ Project : Assigns
Member --o{ Task : Creates
Project --o{ Task : Contains
Member }--o{ Role : Has Roles
Role --o{ Member : Belongs To
User --o{ Member : are Members

@enduml
