@startuml
'https://plantuml.com/sequence-diagram

class RuntimeException{}
class TicketNotFoundException {}
class ProjectNotFoundException{}


RuntimeException <|-- TicketNotFoundException
RuntimeException <|-- ProjectNotFoundException


@enduml